[versions]
agp = "8.8.2"
kotlin = "2.0.0"
coreKtx = "1.16.0"
activityKtx = "1.10.0"
appcompat = "1.7.1"
constraintLayout = "2.2.1"
lifecycleRuntimeKtx = "2.10.0"

retrofit2 = "2.9.0"
okhttp = "4.11.0"

hilt = "2.57.1"
ksp = "2.0.0-1.0.24" # 코틀린버전-ksp버전

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout"}
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx"}

converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit2" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt"}

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

